language: bash

services:
  - docker

env:
  global:
    # change the registry name and username/password to yourself's.
    - ALI_REGISTRY=registry.cn-hangzhou.aliyuncs.com/ybinkubeflow

before_script:
  - echo "$ALI_PASSWORD" | docker login "$ALI_REGISTRY" -u "$ALI_USERNAME" --password-stdin
 
script:
  - echo "start pull and retag and push"
  - |
    for image in $(cat img-list.txt)
    do
      image_name=${image##*/}
      image_name=${image_name%@*}
      docker pull $image
      docker tag $image $ALI_REGISTRY/$image_name
    	
      # push到阿里云仓库
      docker push $ALI_REGISTRY/$image_name
    done

